//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDS_YBWLib_TITLE                101
#define IDS_EXCEPTDESCPFIX_EXCEPTION_WITH_SOURCE_CODE_POSITION 102
#define IDS_EXCEPTDESC_UNEXPECTED       103
#define IDS_EXCEPTDESC_EXTERNALAPI_LIB  104
#define IDS_EXCEPTDESC_EXTERNALAPI_NOLIB 105
#define IDS_EXCEPTDESC_INVALIDPARAM_CLASS_THISPTR 106
#define IDS_EXCEPTDESC_INVALIDPARAM_CLASS 107
#define IDS_EXCEPTDESC_INVALIDPARAM     108
#define IDS_EXCEPTDESC_THREADINIT       109
#define IDS_EXCEPTDESC_WINDOWINIT       110
#define IDS_EXCEPTDESC_CONTROL_CTRLID   111
#define IDS_EXCEPTDESC_CONTROL_NOCTRLID 112
#define IDS_EXCEPTDESCPFIX_HOOKABLE_PROC 113
#define IDS_EXCEPTDESCPFIX_HOOKABLE_PROC_HOOK 114
#define IDS_EXCEPTDESC_HOOK_ALREADY_EXIST 115
#define IDS_EXCEPTDESC_HOOK_NOT_EXIST 116
#define IDS_EXCEPTDESC_HOOK_CYCLIC_DEPENDENCY 117
#define IDS_EXCEPTDESC_HOOK_CYCLIC_DEPENDENCY_DEPCHAINFIRST 118
#define IDS_EXCEPTDESC_HOOK_CYCLIC_DEPENDENCY_DEPCHAININC 119
#define IDS_EXCEPTDESC_HOOK_CYCLIC_DEPENDENCY_DEPCHAINLAST 120
#define IDS_EXCEPTDESC_HOOK_INVOKING_NO_MODIFY 121
#define IDS_EXCEPTDESC_HOOKABLE_PROCEDURE_ALREADY_EXIST 122
#define IDS_EXCEPTDESC_HOOKABLE_PROCEDURE_NOT_EXIST 123
#define IDS_EXCEPTDESC_NOT_IMPLEMENTED  124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
